<?php

class AddressTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('address')->truncate();
        
		\DB::table('address')->insert(array (
			0 => 
			array (
				'id' => 82,
				'customercustomer_id' => 3,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'Bernd',
				'last_name' => 'Obendorfer',
				'street' => 'Lieferstraße',
				'city' => 'Wien',
				'country' => 'Österreich',
				'stateprovince' => 'Wien',
				'zip' => 6060,
				'housenumber' => '2',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2014-06-16 16:51:07',
				'is_published' => 0,
				'slug' => NULL,
			),
			1 => 
			array (
				'id' => 83,
				'customercustomer_id' => 3,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'Bernd',
				'last_name' => 'Obendorfer',
				'street' => 'Rechnungsstraße',
				'city' => 'Wien',
				'country' => 'Österreich',
				'stateprovince' => 'Wien',
				'zip' => 1220,
				'housenumber' => '1',
				'stairway_number' => '2',
				'floor' => '3',
				'appartement_number' => '4',
				'deliveryinformation' => '',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'is_published' => 0,
				'slug' => NULL,
			),
			2 => 
			array (
				'id' => 138,
				'customercustomer_id' => 109,
				'art' => 'Rechnungsadresse',
				'gender' => 'Frau',
				'first_name' => 'Theresa',
				'last_name' => 'Sch&ouml;rkhuber',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-06-16 12:40:56',
				'updated_at' => '2014-06-16 12:40:56',
				'is_published' => 0,
				'slug' => NULL,
			),
			3 => 
			array (
				'id' => 139,
				'customercustomer_id' => 109,
				'art' => 'Lieferadresse',
				'gender' => 'Frau',
				'first_name' => 'Theresa',
				'last_name' => 'Sch&ouml;rkhuber',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-06-16 12:40:56',
				'updated_at' => '2014-06-16 12:40:56',
				'is_published' => 0,
				'slug' => NULL,
			),
			4 => 
			array (
				'id' => 140,
				'customercustomer_id' => 110,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'Robert',
				'last_name' => 'Ginder',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-06-16 18:33:29',
				'updated_at' => '2014-06-16 18:33:29',
				'is_published' => 0,
				'slug' => NULL,
			),
			5 => 
			array (
				'id' => 141,
				'customercustomer_id' => 110,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'Robert',
				'last_name' => 'Ginder',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-06-16 18:33:29',
				'updated_at' => '2014-06-16 18:33:29',
				'is_published' => 0,
				'slug' => NULL,
			),
			6 => 
			array (
				'id' => 142,
				'customercustomer_id' => 111,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'mau',
				'last_name' => 'kau',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:20:22',
				'updated_at' => '2014-07-07 10:20:22',
				'is_published' => 0,
				'slug' => NULL,
			),
			7 => 
			array (
				'id' => 143,
				'customercustomer_id' => 111,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'mau',
				'last_name' => 'kau',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:20:22',
				'updated_at' => '2014-07-07 10:20:22',
				'is_published' => 0,
				'slug' => NULL,
			),
			8 => 
			array (
				'id' => 144,
				'customercustomer_id' => 112,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'daSDSA',
				'last_name' => 'DSAFDSA',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:36:08',
				'updated_at' => '2014-07-07 10:36:08',
				'is_published' => 0,
				'slug' => NULL,
			),
			9 => 
			array (
				'id' => 145,
				'customercustomer_id' => 112,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'daSDSA',
				'last_name' => 'DSAFDSA',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:36:08',
				'updated_at' => '2014-07-07 10:36:08',
				'is_published' => 0,
				'slug' => NULL,
			),
			10 => 
			array (
				'id' => 146,
				'customercustomer_id' => 113,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'safda',
				'last_name' => 'adsfa',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:49:24',
				'updated_at' => '2014-07-07 10:49:24',
				'is_published' => 0,
				'slug' => NULL,
			),
			11 => 
			array (
				'id' => 147,
				'customercustomer_id' => 113,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'safda',
				'last_name' => 'adsfa',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:49:24',
				'updated_at' => '2014-07-07 10:49:24',
				'is_published' => 0,
				'slug' => NULL,
			),
			12 => 
			array (
				'id' => 148,
				'customercustomer_id' => 114,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'dsafsadf',
				'last_name' => 'adsfdsa',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:56:01',
				'updated_at' => '2014-07-07 10:56:01',
				'is_published' => 0,
				'slug' => NULL,
			),
			13 => 
			array (
				'id' => 149,
				'customercustomer_id' => 114,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'dsafsadf',
				'last_name' => 'adsfdsa',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:56:01',
				'updated_at' => '2014-07-07 10:56:01',
				'is_published' => 0,
				'slug' => NULL,
			),
			14 => 
			array (
				'id' => 150,
				'customercustomer_id' => 115,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'kokok',
				'last_name' => 'hihi',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:57:40',
				'updated_at' => '2014-07-07 10:57:40',
				'is_published' => 0,
				'slug' => NULL,
			),
			15 => 
			array (
				'id' => 151,
				'customercustomer_id' => 115,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'kokok',
				'last_name' => 'hihi',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-07 10:57:40',
				'updated_at' => '2014-07-07 10:57:40',
				'is_published' => 0,
				'slug' => NULL,
			),
			16 => 
			array (
				'id' => 152,
				'customercustomer_id' => 116,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'dsafdsaf',
				'last_name' => 'dsafdsaf',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-08 06:59:40',
				'updated_at' => '2014-07-08 06:59:40',
				'is_published' => 0,
				'slug' => NULL,
			),
			17 => 
			array (
				'id' => 153,
				'customercustomer_id' => 116,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'dsafdsaf',
				'last_name' => 'dsafdsaf',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-08 06:59:40',
				'updated_at' => '2014-07-08 06:59:40',
				'is_published' => 0,
				'slug' => NULL,
			),
			18 => 
			array (
				'id' => 154,
				'customercustomer_id' => 125,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'TestBernd',
				'last_name' => 'dddddd',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-25 10:25:59',
				'updated_at' => '2014-07-25 10:25:59',
				'is_published' => 0,
				'slug' => NULL,
			),
			19 => 
			array (
				'id' => 155,
				'customercustomer_id' => 125,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'TestBernd',
				'last_name' => 'dddddd',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-07-25 10:25:59',
				'updated_at' => '2014-07-25 10:25:59',
				'is_published' => 0,
				'slug' => NULL,
			),
			20 => 
			array (
				'id' => 218,
				'customercustomer_id' => 175,
				'art' => 'Rechnungsadresse',
				'gender' => 'Frau',
				'first_name' => 'Mucki',
				'last_name' => 'Fatz',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-08-01 09:44:36',
				'updated_at' => '2014-08-01 09:44:36',
				'is_published' => 0,
				'slug' => NULL,
			),
			21 => 
			array (
				'id' => 219,
				'customercustomer_id' => 175,
				'art' => 'Lieferadresse',
				'gender' => 'Frau',
				'first_name' => 'Mucki',
				'last_name' => 'Fatz',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-08-01 09:44:36',
				'updated_at' => '2014-08-01 09:44:36',
				'is_published' => 0,
				'slug' => NULL,
			),
			22 => 
			array (
				'id' => 220,
				'customercustomer_id' => 176,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'maus',
				'last_name' => 'bar',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-08-01 10:09:27',
				'updated_at' => '2014-08-01 10:09:27',
				'is_published' => 0,
				'slug' => NULL,
			),
			23 => 
			array (
				'id' => 221,
				'customercustomer_id' => 176,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'maus',
				'last_name' => 'bar',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-08-01 10:09:27',
				'updated_at' => '2014-08-01 10:09:27',
				'is_published' => 0,
				'slug' => NULL,
			),
			24 => 
			array (
				'id' => 222,
				'customercustomer_id' => 177,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'a',
				'last_name' => 'b',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-08-01 10:10:59',
				'updated_at' => '2014-08-01 10:10:59',
				'is_published' => 0,
				'slug' => NULL,
			),
			25 => 
			array (
				'id' => 223,
				'customercustomer_id' => 177,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'a',
				'last_name' => 'b',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-08-01 10:10:59',
				'updated_at' => '2014-08-01 10:10:59',
				'is_published' => 0,
				'slug' => NULL,
			),
			26 => 
			array (
				'id' => 224,
				'customercustomer_id' => 178,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'dsafas',
				'last_name' => 'dsafa',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-08-01 10:25:01',
				'updated_at' => '2014-08-01 10:25:01',
				'is_published' => 0,
				'slug' => NULL,
			),
			27 => 
			array (
				'id' => 225,
				'customercustomer_id' => 178,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'dsafas',
				'last_name' => 'dsafa',
				'street' => '',
				'city' => '',
				'country' => '',
				'stateprovince' => '',
				'zip' => 0,
				'housenumber' => '',
				'stairway_number' => '',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-08-01 10:25:01',
				'updated_at' => '2014-08-01 10:25:01',
				'is_published' => 0,
				'slug' => NULL,
			),
			28 => 
			array (
				'id' => 226,
				'customercustomer_id' => 179,
				'art' => 'Rechnungsadresse',
				'gender' => 'Herr',
				'first_name' => 'Robert',
				'last_name' => 'Melk',
				'street' => 'Ochsengasse',
				'city' => 'Niederösterreich',
				'country' => 'Österreich',
				'stateprovince' => '',
				'zip' => 2040,
				'housenumber' => '1',
				'stairway_number' => '2',
				'floor' => '',
				'appartement_number' => '',
				'deliveryinformation' => '',
				'created_at' => '2014-08-05 05:46:55',
				'updated_at' => '2014-08-05 05:46:55',
				'is_published' => 0,
				'slug' => NULL,
			),
			29 => 
			array (
				'id' => 227,
				'customercustomer_id' => 179,
				'art' => 'Lieferadresse',
				'gender' => 'Herr',
				'first_name' => 'Robert',
				'last_name' => 'Melk',
				'street' => 'Okalastrasse',
				'city' => 'Wien',
				'country' => 'Österreich',
				'stateprovince' => '',
				'zip' => 1220,
				'housenumber' => '1',
				'stairway_number' => '2',
				'floor' => '3',
				'appartement_number' => '4',
				'deliveryinformation' => '',
				'created_at' => '2014-08-05 05:46:55',
				'updated_at' => '2014-08-05 05:46:55',
				'is_published' => 0,
				'slug' => NULL,
			),
		));
	}

}
