<?php

class CustomersTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('customers')->truncate();
        
		\DB::table('customers')->insert(array (
			0 => 
			array (
				'id' => 3,
				'customers_groups_id' => 0,
				'first_name' => 'Bernd',
				'last_name' => 'Obendorfer',
				'datetime' => '',
				'kundeseit' => '28.04.2014 13:20:38',
				'abobox' => '2P-3R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '0',
				'abobiere' => '0',
				'anzahlobstboxen' => '0',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-04-19 04:02:36',
				'updated_at' => '2014-05-04 13:56:55',
				'is_published' => 1,
				'gender' => 'Herr',
			),
			1 => 
			array (
				'id' => 171,
				'customers_groups_id' => 0,
				'first_name' => 'Tom',
				'last_name' => 'Reichel',
				'datetime' => '',
				'kundeseit' => '06.05.2014',
				'abobox' => '2P-3R-C',
				'abolieferung' => '23.04.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '1',
				'abobiere' => '1',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 17:59:17',
				'updated_at' => '2014-05-04 18:48:31',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			2 => 
			array (
				'id' => 172,
				'customers_groups_id' => 0,
				'first_name' => 'Robert',
				'last_name' => 'Ginder',
				'datetime' => '',
				'kundeseit' => '23.01.1999',
				'abobox' => '4P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '0',
				'abobiere' => '1',
				'anzahlobstboxen' => '0',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 18:50:17',
				'updated_at' => '2014-05-04 18:50:17',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			3 => 
			array (
				'id' => 173,
				'customers_groups_id' => 0,
				'first_name' => 'Maria',
				'last_name' => 'Holler',
				'datetime' => '',
				'kundeseit' => '07.05.2014',
				'abobox' => '4P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 18:54:38',
				'updated_at' => '2014-05-04 18:54:38',
				'is_published' => 0,
				'gender' => 'Frau',
			),
			4 => 
			array (
				'id' => 174,
				'customers_groups_id' => 0,
				'first_name' => 'Herbert',
				'last_name' => 'Holler',
				'datetime' => '',
				'kundeseit' => '07.05.2014',
				'abobox' => '4P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '0',
				'abobiere' => '1',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 18:58:03',
				'updated_at' => '2014-05-04 18:58:03',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			5 => 
			array (
				'id' => 175,
				'customers_groups_id' => 0,
				'first_name' => 'Sandra',
				'last_name' => 'Meier',
				'datetime' => '',
				'kundeseit' => '01.05.2014',
				'abobox' => '3P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 18:58:55',
				'updated_at' => '2014-05-04 18:58:55',
				'is_published' => 0,
				'gender' => 'Frau',
			),
			6 => 
			array (
				'id' => 176,
				'customers_groups_id' => 0,
				'first_name' => 'Dragan',
				'last_name' => 'Vukic',
				'datetime' => '',
				'kundeseit' => '02.04.2014',
				'abobox' => '1P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 18:59:34',
				'updated_at' => '2014-05-04 18:59:34',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			7 => 
			array (
				'id' => 178,
				'customers_groups_id' => 0,
				'first_name' => 'Markus',
				'last_name' => 'Reh',
				'datetime' => '',
				'kundeseit' => '13.01.1999',
				'abobox' => '4P-5R-C',
				'abolieferung' => '23.04.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '0',
				'abobiere' => '1',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 19:51:28',
				'updated_at' => '2014-05-04 21:15:57',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			8 => 
			array (
				'id' => 179,
				'customers_groups_id' => 0,
				'first_name' => 'Hans',
				'last_name' => 'Hahn',
				'datetime' => '',
				'kundeseit' => '03.05.2010',
				'abobox' => '2P-3R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '0',
				'abobiere' => '1',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 19:57:59',
				'updated_at' => '2014-05-04 19:59:33',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			9 => 
			array (
				'id' => 180,
				'customers_groups_id' => 0,
				'first_name' => 'Jörg',
				'last_name' => 'Gruber',
				'datetime' => '',
				'kundeseit' => '02.05.2010',
				'abobox' => '2P-3R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '1',
				'abobiere' => '1',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 19:58:31',
				'updated_at' => '2014-05-04 19:58:31',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			10 => 
			array (
				'id' => 181,
				'customers_groups_id' => 0,
				'first_name' => 'Mike',
				'last_name' => 'Röhrer',
				'datetime' => '',
				'kundeseit' => '01.02.2010',
				'abobox' => '4P-3R-C',
				'abolieferung' => '10.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '0',
				'abobiere' => '0',
				'anzahlobstboxen' => '0',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 19:59:17',
				'updated_at' => '2014-05-04 19:59:17',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			11 => 
			array (
				'id' => 182,
				'customers_groups_id' => 0,
				'first_name' => 'mauki',
				'last_name' => 'Vukic',
				'datetime' => '',
				'kundeseit' => '02.04.2014',
				'abobox' => '1P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'Retailer',
				'created_at' => '2014-05-04 18:59:34',
				'updated_at' => '2014-05-04 18:59:34',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			12 => 
			array (
				'id' => 183,
				'customers_groups_id' => 0,
				'first_name' => 'Mauniz',
				'last_name' => 'Vukic',
				'datetime' => '',
				'kundeseit' => '02.04.2014',
				'abobox' => '1P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'Retailer',
				'created_at' => '2014-05-04 18:59:34',
				'updated_at' => '2014-05-04 18:59:34',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			13 => 
			array (
				'id' => 184,
				'customers_groups_id' => 0,
				'first_name' => 'Flocki',
				'last_name' => 'Vukic',
				'datetime' => '',
				'kundeseit' => '02.04.2014',
				'abobox' => '1P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Kein Abo',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'Retailer',
				'created_at' => '2014-05-04 18:59:34',
				'updated_at' => '2014-05-04 18:59:34',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			14 => 
			array (
				'id' => 185,
				'customers_groups_id' => 0,
				'first_name' => 'Sandra',
				'last_name' => 'Meier',
				'datetime' => '',
				'kundeseit' => '01.05.2014',
				'abobox' => '3P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Gesperrt',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Aktiv',
				'gruppen' => 'General',
				'created_at' => '2014-05-04 18:58:55',
				'updated_at' => '2014-05-04 18:58:55',
				'is_published' => 0,
				'gender' => 'Frau',
			),
			15 => 
			array (
				'id' => 186,
				'customers_groups_id' => 0,
				'first_name' => 'Mike',
				'last_name' => 'Röhrer',
				'datetime' => '',
				'kundeseit' => '01.02.2010',
				'abobox' => '4P-3R-C',
				'abolieferung' => '10.05.2014',
				'abotyp' => 'Einwöchig',
				'aboweine' => '0',
				'abobiere' => '0',
				'anzahlobstboxen' => '0',
				'abostatus' => 'Inaktiv',
				'gruppen' => 'Allianz',
				'created_at' => '2014-05-04 19:59:17',
				'updated_at' => '2014-05-04 19:59:17',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			16 => 
			array (
				'id' => 187,
				'customers_groups_id' => 0,
				'first_name' => 'Sandra',
				'last_name' => 'Meier',
				'datetime' => '',
				'kundeseit' => '01.05.2014',
				'abobox' => '3P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Vierwöchig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Pausiert',
				'gruppen' => 'Retailer',
				'created_at' => '2014-05-04 18:58:55',
				'updated_at' => '2014-05-04 18:58:55',
				'is_published' => 0,
				'gender' => 'Frau',
			),
			17 => 
			array (
				'id' => 188,
				'customers_groups_id' => 0,
				'first_name' => 'Richard',
				'last_name' => 'Meier',
				'datetime' => '',
				'kundeseit' => '01.05.2014',
				'abobox' => '3P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Vierwöchig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Pausiert',
				'gruppen' => 'Deleted',
				'created_at' => '2014-05-04 18:58:55',
				'updated_at' => '2014-05-04 18:58:55',
				'is_published' => 0,
				'gender' => 'Frau',
			),
			18 => 
			array (
				'id' => 189,
				'customers_groups_id' => 0,
				'first_name' => 'Robert',
				'last_name' => 'Meier',
				'datetime' => '',
				'kundeseit' => '01.05.2014',
				'abobox' => '3P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einmalig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Pausiert',
				'gruppen' => 'Keine Mails',
				'created_at' => '2014-05-04 18:58:55',
				'updated_at' => '2014-05-04 18:58:55',
				'is_published' => 0,
				'gender' => 'Frau',
			),
			19 => 
			array (
				'id' => 190,
				'customers_groups_id' => 0,
				'first_name' => 'Richard',
				'last_name' => 'Ranz',
				'datetime' => '',
				'kundeseit' => '01.05.2014',
				'abobox' => '3P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Vierwöchig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Pausiert',
				'gruppen' => 'Deleted',
				'created_at' => '2014-05-04 18:58:55',
				'updated_at' => '2014-05-04 18:58:55',
				'is_published' => 0,
				'gender' => 'Frau',
			),
			20 => 
			array (
				'id' => 191,
				'customers_groups_id' => 0,
				'first_name' => 'Ralsfi',
				'last_name' => 'Meier',
				'datetime' => '',
				'kundeseit' => '01.05.2014',
				'abobox' => '3P-5R-C',
				'abolieferung' => '05.05.2014',
				'abotyp' => 'Einmalig',
				'aboweine' => '1',
				'abobiere' => '0',
				'anzahlobstboxen' => '1',
				'abostatus' => 'Pausiert',
				'gruppen' => 'Keine Mails',
				'created_at' => '2014-05-04 18:58:55',
				'updated_at' => '2014-05-04 18:58:55',
				'is_published' => 0,
				'gender' => 'Frau',
			),
			21 => 
			array (
				'id' => 193,
				'customers_groups_id' => 0,
				'first_name' => 'Bernd',
				'last_name' => 'Obendorfer',
				'datetime' => '06 Mai 2014',
				'kundeseit' => '',
				'abobox' => '55dd5',
				'abolieferung' => '',
				'abotyp' => 'Vierwöchig',
				'aboweine' => '',
				'abobiere' => '',
				'anzahlobstboxen' => '',
				'abostatus' => 'Flash Sale Produkt',
				'gruppen' => 'Wholesale',
				'created_at' => '2014-05-30 14:16:10',
				'updated_at' => '2014-05-30 14:27:26',
				'is_published' => 0,
				'gender' => 'Herr',
			),
			22 => 
			array (
				'id' => 194,
				'customers_groups_id' => 0,
				'first_name' => 'Eier',
				'last_name' => 'Kopf',
				'datetime' => '31 Mai 2014',
				'kundeseit' => 'Immer',
				'abobox' => 'Keine',
				'abolieferung' => 'Klar',
				'abotyp' => 'Zweiwöchig',
				'aboweine' => '1',
				'abobiere' => '2',
				'anzahlobstboxen' => '3',
				'abostatus' => 'Pausiert',
				'gruppen' => 'Existing Customers',
				'created_at' => '2014-05-30 14:30:18',
				'updated_at' => '2014-05-30 14:30:18',
				'is_published' => 0,
				'gender' => 'Herr',
			),
		));
	}

}
