<?php

class G3TableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('g3')->truncate();
        
		\DB::table('g3')->insert(array (
			0 => 
			array (
				'id' => 49,
				'name' => '20130504_230205.jpg',
				'size' => 2009898,
				'type' => 'image/jpeg',
				'url' => NULL,
				'title' => NULL,
				'description' => 'h',
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			1 => 
			array (
				'id' => 55,
				'name' => 'walmart_grey.png',
				'size' => 3895,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			2 => 
			array (
				'id' => 56,
				'name' => 'vadafone.png',
				'size' => 12196,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			3 => 
			array (
				'id' => 57,
				'name' => 'walmart.png',
				'size' => 4068,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			4 => 
			array (
				'id' => 58,
				'name' => 'vadafone_grey.png',
				'size' => 9046,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			5 => 
			array (
				'id' => 59,
				'name' => 'spinworkx.png',
				'size' => 8625,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			6 => 
			array (
				'id' => 60,
				'name' => 'spinworkx_grey.png',
				'size' => 5663,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			7 => 
			array (
				'id' => 61,
				'name' => 'natural.png',
				'size' => 4575,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			8 => 
			array (
				'id' => 62,
				'name' => 'motogp_grey.png',
				'size' => 5584,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			9 => 
			array (
				'id' => 63,
				'name' => 'gamescast.png',
				'size' => 4212,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			10 => 
			array (
				'id' => 64,
				'name' => 'gamescast_grey.png',
				'size' => 3928,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			11 => 
			array (
				'id' => 65,
				'name' => 'motogp.png',
				'size' => 7027,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			12 => 
			array (
				'id' => 66,
				'name' => 'natural_grey.png',
				'size' => 3928,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			13 => 
			array (
				'id' => 67,
				'name' => 'cocacola.png',
				'size' => 10780,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			14 => 
			array (
				'id' => 68,
				'name' => 'igneus_grey.png',
				'size' => 3270,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			15 => 
			array (
				'id' => 69,
				'name' => 'everyday.png',
				'size' => 8189,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			16 => 
			array (
				'id' => 70,
				'name' => 'cocacola_grey.png',
				'size' => 7091,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			17 => 
			array (
				'id' => 71,
				'name' => 'igneus.png',
				'size' => 3773,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			18 => 
			array (
				'id' => 72,
				'name' => 'everyday_grey.png',
				'size' => 5965,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			19 => 
			array (
				'id' => 73,
				'name' => 'shell.png',
				'size' => 8960,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			20 => 
			array (
				'id' => 74,
				'name' => 'shell_grey.png',
				'size' => 6169,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			21 => 
			array (
				'id' => 75,
				'name' => 'aztec.png',
				'size' => 11977,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			22 => 
			array (
				'id' => 76,
				'name' => 'aztec_grey.png',
				'size' => 9133,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			23 => 
			array (
				'id' => 77,
				'name' => 'cisco_grey.png',
				'size' => 5985,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			24 => 
			array (
				'id' => 78,
				'name' => 'cisco.png',
				'size' => 8039,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			25 => 
			array (
				'id' => 79,
				'name' => 'hp_grey.png',
				'size' => 7296,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
			26 => 
			array (
				'id' => 80,
				'name' => 'hp.png',
				'size' => 7536,
				'type' => 'image/png',
				'url' => NULL,
				'title' => NULL,
				'description' => NULL,
				'ordner' => NULL,
				'contributor' => '',
				'uploadedOn' => '',
			),
		));
	}

}
