<?php

class LogisticianmanagerTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('logisticianmanager')->truncate();
        
		\DB::table('logisticianmanager')->insert(array (
			0 => 
			array (
				'id' => 1,
				'street' => 'Dummy',
				'streetno' => 'Dummy',
				'city' => 'Dummy',
				'stateprovince' => 'Dummy',
				'zip' => 0,
				'country_id' => '',
				'contactPerson' => 'Dummy',
				'email' => 'Dummy',
				'phone' => 'Dummy',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'is_published' => 0,
				'name' => 'Bitte Auswahl treffen.',
			),
			1 => 
			array (
				'id' => 10,
				'street' => 'Golfgasse 3',
				'streetno' => '
',
				'city' => 'Wien',
				'stateprovince' => 'Wien',
				'zip' => 1220,
				'country_id' => 'Österreich',
				'contactPerson' => 'Rolf Niemand',
				'email' => 'rolf.niemand@chello.at',
				'phone' => '06655565569',
				'created_at' => '2014-04-19 04:02:36',
				'updated_at' => '2014-05-07 16:11:51',
				'is_published' => 0,
				'name' => 'Niemand GmbH',
			),
			2 => 
			array (
				'id' => 171,
				'street' => 'Meiergasse 5',
				'streetno' => '
',
				'city' => 'Salzburg Stadt',
				'stateprovince' => 'Salzburg',
				'zip' => 5020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Margit Zeigelt',
				'email' => 'm.zweigelt@chello.at',
				'phone' => '05/5656569',
				'created_at' => '2014-05-04 17:59:17',
				'updated_at' => '2014-05-07 16:12:40',
				'is_published' => 0,
				'name' => 'Zeigelt Logistics',
			),
			3 => 
			array (
				'id' => 186,
				'street' => 'Gonzigasse 7',
				'streetno' => '',
				'city' => 'Insbruck',
				'stateprovince' => 'Tirol',
				'zip' => 7020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Hr Markus Fritzberger',
				'email' => 'markus.fritzberger@chello.at',
				'phone' => '01/504565a',
				'created_at' => '2014-05-06 21:37:06',
				'updated_at' => '2014-05-11 18:58:05',
				'is_published' => 0,
				'name' => 'Mutzifatzi GmbH',
			),
			4 => 
			array (
				'id' => 187,
				'street' => 'franzimaunzgasse 7',
				'streetno' => '',
				'city' => 'St Pölten',
				'stateprovince' => 'Österreich',
				'zip' => 5040,
				'country_id' => 'adsfdsaf',
				'contactPerson' => 'Frau Miki',
				'email' => '',
				'phone' => '06606060',
				'created_at' => '2014-05-11 18:59:06',
				'updated_at' => '2014-05-18 18:24:09',
				'is_published' => 0,
				'name' => 'Arg KG',
			),
			5 => 
			array (
				'id' => 188,
				'street' => 'Meiergasse 5',
				'streetno' => '
',
				'city' => 'Salzburg Stadt',
				'stateprovince' => 'Salzburg',
				'zip' => 5020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Margit Zeigelt',
				'email' => 'm.zweigelt@chello.at',
				'phone' => '05/5656569',
				'created_at' => '2014-05-04 17:59:17',
				'updated_at' => '2014-05-07 16:12:40',
				'is_published' => 0,
				'name' => 'Zeigelt Logistics',
			),
			6 => 
			array (
				'id' => 189,
				'street' => 'Gonzigasse 7',
				'streetno' => '',
				'city' => 'Insbruck',
				'stateprovince' => 'Tirol',
				'zip' => 8020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Hr Markus Fritzberger',
				'email' => 'markus.fritzberger@chello.at',
				'phone' => '01/504565a',
				'created_at' => '2014-05-06 21:37:06',
				'updated_at' => '2014-05-11 18:58:05',
				'is_published' => 0,
				'name' => 'Mutzifatzi GmbH',
			),
			7 => 
			array (
				'id' => 190,
				'street' => 'kauzgasse',
				'streetno' => '
',
				'city' => 'Salzburg Stadt',
				'stateprovince' => 'Salzburg',
				'zip' => 5020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Margit Zeigelt',
				'email' => 'm.zweigelt@chello.at',
				'phone' => '05/5656569',
				'created_at' => '2014-05-04 17:59:17',
				'updated_at' => '2014-05-07 16:12:40',
				'is_published' => 0,
				'name' => 'Zeigelt Logistics',
			),
			8 => 
			array (
				'id' => 191,
				'street' => 'Rachgasse 4',
				'streetno' => '
',
				'city' => 'Wien',
				'stateprovince' => 'Wien',
				'zip' => 1220,
				'country_id' => 'Österreich',
				'contactPerson' => 'Rolf maka',
				'email' => 'rolf.niemand@chello.at',
				'phone' => '06655565569',
				'created_at' => '2014-04-19 04:02:36',
				'updated_at' => '2014-05-07 16:11:51',
				'is_published' => 0,
				'name' => 'Niemand GmbH',
			),
			9 => 
			array (
				'id' => 193,
				'street' => 'fuchsgasse 8',
				'streetno' => '',
				'city' => 'Kärnten',
				'stateprovince' => 'Tirol',
				'zip' => 7020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Hr Markus Fritzberger',
				'email' => 'markus.fritzberger@chello.at',
				'phone' => '01/504565a',
				'created_at' => '2014-05-06 21:37:06',
				'updated_at' => '2014-05-11 18:58:05',
				'is_published' => 0,
				'name' => 'mualilaug GmbH',
			),
			10 => 
			array (
				'id' => 194,
				'street' => 'rudolfgasse 7',
				'streetno' => '',
				'city' => 'Graz',
				'stateprovince' => 'Tirol',
				'zip' => 5645,
				'country_id' => 'Österreich',
				'contactPerson' => 'Hr Markus Fritzberger',
				'email' => 'markus.fritzberger@chello.at',
				'phone' => '01/504565a',
				'created_at' => '2014-05-06 21:37:06',
				'updated_at' => '2014-05-11 18:58:05',
				'is_published' => 0,
				'name' => 'Raunzigmbh GmbH',
			),
			11 => 
			array (
				'id' => 195,
				'street' => 'franzimaunzgasse 7',
				'streetno' => '',
				'city' => 'St Pölten',
				'stateprovince' => 'Österreich',
				'zip' => 5040,
				'country_id' => 'adsfdsaf',
				'contactPerson' => 'Frau Miki',
				'email' => '',
				'phone' => '06606060',
				'created_at' => '2014-05-11 18:59:06',
				'updated_at' => '2014-05-18 18:24:09',
				'is_published' => 0,
				'name' => 'Arg KG',
			),
			12 => 
			array (
				'id' => 196,
				'street' => 'Dsdaf',
				'streetno' => 'asdf',
				'city' => 'sadf',
				'stateprovince' => 'dsaf',
				'zip' => 0,
				'country_id' => '',
				'contactPerson' => 'afds',
				'email' => 'dsaf',
				'phone' => 'dsaf',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'is_published' => 0,
				'name' => 'Bitte Auswahl treffen.',
			),
			13 => 
			array (
				'id' => 197,
				'street' => 'kauzgasse',
				'streetno' => '
',
				'city' => 'Salzburg Stadt',
				'stateprovince' => 'Salzburg',
				'zip' => 5020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Margit Zeigelt',
				'email' => 'm.zweigelt@chello.at',
				'phone' => '05/5656569',
				'created_at' => '2014-05-04 17:59:17',
				'updated_at' => '2014-05-07 16:12:40',
				'is_published' => 0,
				'name' => 'Zeigelt Logistics',
			),
			14 => 
			array (
				'id' => 198,
				'street' => 'Gonzigasse 7',
				'streetno' => '',
				'city' => 'Insbruck',
				'stateprovince' => 'Tirol',
				'zip' => 8020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Hr Markus Fritzberger',
				'email' => 'markus.fritzberger@chello.at',
				'phone' => '01/504565a',
				'created_at' => '2014-05-06 21:37:06',
				'updated_at' => '2014-05-11 18:58:05',
				'is_published' => 0,
				'name' => 'Mutzifatzi GmbH',
			),
			15 => 
			array (
				'id' => 199,
				'street' => 'Meiergasse 5',
				'streetno' => '
',
				'city' => 'Salzburg Stadt',
				'stateprovince' => 'Salzburg',
				'zip' => 5020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Margit Zeigelt',
				'email' => 'm.zweigelt@chello.at',
				'phone' => '05/5656569',
				'created_at' => '2014-05-04 17:59:17',
				'updated_at' => '2014-05-07 16:12:40',
				'is_published' => 0,
				'name' => 'Zeigelt Logistics',
			),
			16 => 
			array (
				'id' => 200,
				'street' => 'sadfsadf',
				'streetno' => 'sadfsad',
				'city' => 'dsaf',
				'stateprovince' => 'dsafsadfsad',
				'zip' => 0,
				'country_id' => '',
				'contactPerson' => 'Ddsafdsa',
				'email' => 'dsafsadf',
				'phone' => 'Dudsafdsaf',
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
				'is_published' => 0,
				'name' => 'Bitte Auswahl treffen.',
			),
			17 => 
			array (
				'id' => 201,
				'street' => 'kauzsgasse',
				'streetno' => '
',
				'city' => 'Salzburg Stadt',
				'stateprovince' => 'Salzburg',
				'zip' => 5020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Margit Zeigelt',
				'email' => 'm.zweigelt@chello.at',
				'phone' => '05/5656569',
				'created_at' => '2014-05-04 17:59:17',
				'updated_at' => '2014-05-07 16:12:40',
				'is_published' => 0,
				'name' => 'Zeigelt Logistics',
			),
			18 => 
			array (
				'id' => 202,
				'street' => 'fuchsgassse 8',
				'streetno' => '',
				'city' => 'Kärnten',
				'stateprovince' => 'Tirol',
				'zip' => 7020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Hr Markus Fritzberger',
				'email' => 'markus.fritzberger@chello.at',
				'phone' => '01/504565a',
				'created_at' => '2014-05-06 21:37:06',
				'updated_at' => '2014-05-11 18:58:05',
				'is_published' => 0,
				'name' => 'mualilaug GmbH',
			),
			19 => 
			array (
				'id' => 203,
				'street' => 'kauzgasse',
				'streetno' => '
',
				'city' => 'Salzburg Stadt',
				'stateprovince' => 'Salzburg',
				'zip' => 5020,
				'country_id' => 'Österreissch',
				'contactPerson' => 'Margit Zeigelt',
				'email' => 'm.zweigelt@chello.at',
				'phone' => '05/5656569',
				'created_at' => '2014-05-04 17:59:17',
				'updated_at' => '2014-05-07 16:12:40',
				'is_published' => 0,
				'name' => 'Zeigelt Logistics',
			),
			20 => 
			array (
				'id' => 204,
				'street' => 'kauzgasse',
				'streetno' => '
',
				'city' => 'Salzburg Stadt',
				'stateprovince' => 'Salzburg',
				'zip' => 5020,
				'country_id' => 'Österreich',
				'contactPerson' => 'Margisst Zeigelt',
				'email' => 'm.zweigelt@chello.at',
				'phone' => '05/5656569',
				'created_at' => '2014-05-04 17:59:17',
				'updated_at' => '2014-05-07 16:12:40',
				'is_published' => 0,
				'name' => 'Zeigelt Logistics',
			),
		));
	}

}
