<?php

class ThrottleTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('throttle')->truncate();
        
		\DB::table('throttle')->insert(array (
			0 => 
			array (
				'id' => 1,
				'user_id' => 1,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			1 => 
			array (
				'id' => 2,
				'user_id' => 2,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			2 => 
			array (
				'id' => 3,
				'user_id' => 3,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => '2014-07-11 09:16:46',
				'suspended_at' => NULL,
				'banned_at' => '2014-06-09 22:46:54',
			),
			3 => 
			array (
				'id' => 4,
				'user_id' => 4,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			4 => 
			array (
				'id' => 5,
				'user_id' => 5,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			5 => 
			array (
				'id' => 6,
				'user_id' => 6,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			6 => 
			array (
				'id' => 7,
				'user_id' => 7,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			7 => 
			array (
				'id' => 8,
				'user_id' => 8,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			8 => 
			array (
				'id' => 9,
				'user_id' => 20,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			9 => 
			array (
				'id' => 10,
				'user_id' => 21,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			10 => 
			array (
				'id' => 11,
				'user_id' => 37,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			11 => 
			array (
				'id' => 12,
				'user_id' => 38,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			12 => 
			array (
				'id' => 13,
				'user_id' => 40,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			13 => 
			array (
				'id' => 14,
				'user_id' => 41,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			14 => 
			array (
				'id' => 15,
				'user_id' => 34,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			15 => 
			array (
				'id' => 16,
				'user_id' => 35,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			16 => 
			array (
				'id' => 17,
				'user_id' => 36,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			17 => 
			array (
				'id' => 18,
				'user_id' => 39,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			18 => 
			array (
				'id' => 19,
				'user_id' => 42,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			19 => 
			array (
				'id' => 20,
				'user_id' => 43,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			20 => 
			array (
				'id' => 21,
				'user_id' => 44,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			21 => 
			array (
				'id' => 22,
				'user_id' => 45,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			22 => 
			array (
				'id' => 23,
				'user_id' => 46,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			23 => 
			array (
				'id' => 24,
				'user_id' => 47,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			24 => 
			array (
				'id' => 25,
				'user_id' => 48,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			25 => 
			array (
				'id' => 26,
				'user_id' => 49,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			26 => 
			array (
				'id' => 27,
				'user_id' => 50,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			27 => 
			array (
				'id' => 28,
				'user_id' => 51,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			28 => 
			array (
				'id' => 29,
				'user_id' => 52,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			29 => 
			array (
				'id' => 30,
				'user_id' => 53,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			30 => 
			array (
				'id' => 31,
				'user_id' => 54,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			31 => 
			array (
				'id' => 32,
				'user_id' => 55,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			32 => 
			array (
				'id' => 33,
				'user_id' => 56,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			33 => 
			array (
				'id' => 34,
				'user_id' => 58,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			34 => 
			array (
				'id' => 35,
				'user_id' => 57,
				'ip_address' => NULL,
				'attempts' => 3,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => '2014-04-28 05:25:07',
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			35 => 
			array (
				'id' => 36,
				'user_id' => 59,
				'ip_address' => NULL,
				'attempts' => 1,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => '2014-04-23 21:35:33',
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			36 => 
			array (
				'id' => 37,
				'user_id' => 60,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			37 => 
			array (
				'id' => 38,
				'user_id' => 61,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			38 => 
			array (
				'id' => 39,
				'user_id' => 62,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			39 => 
			array (
				'id' => 40,
				'user_id' => 65,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			40 => 
			array (
				'id' => 41,
				'user_id' => 67,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			41 => 
			array (
				'id' => 42,
				'user_id' => 68,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			42 => 
			array (
				'id' => 43,
				'user_id' => 84,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			43 => 
			array (
				'id' => 44,
				'user_id' => 85,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			44 => 
			array (
				'id' => 45,
				'user_id' => 86,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			45 => 
			array (
				'id' => 46,
				'user_id' => 87,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			46 => 
			array (
				'id' => 47,
				'user_id' => 88,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			47 => 
			array (
				'id' => 48,
				'user_id' => 89,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			48 => 
			array (
				'id' => 49,
				'user_id' => 90,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			49 => 
			array (
				'id' => 50,
				'user_id' => 91,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			50 => 
			array (
				'id' => 51,
				'user_id' => 92,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			51 => 
			array (
				'id' => 52,
				'user_id' => 93,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			52 => 
			array (
				'id' => 53,
				'user_id' => 94,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			53 => 
			array (
				'id' => 54,
				'user_id' => 17,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			54 => 
			array (
				'id' => 55,
				'user_id' => 18,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			55 => 
			array (
				'id' => 56,
				'user_id' => 19,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			56 => 
			array (
				'id' => 57,
				'user_id' => 22,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			57 => 
			array (
				'id' => 58,
				'user_id' => 23,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			58 => 
			array (
				'id' => 59,
				'user_id' => 24,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			59 => 
			array (
				'id' => 60,
				'user_id' => 25,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			60 => 
			array (
				'id' => 61,
				'user_id' => 26,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			61 => 
			array (
				'id' => 62,
				'user_id' => 27,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			62 => 
			array (
				'id' => 63,
				'user_id' => 31,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			63 => 
			array (
				'id' => 64,
				'user_id' => 32,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			64 => 
			array (
				'id' => 65,
				'user_id' => 33,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			65 => 
			array (
				'id' => 66,
				'user_id' => 70,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			66 => 
			array (
				'id' => 67,
				'user_id' => 71,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			67 => 
			array (
				'id' => 68,
				'user_id' => 72,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			68 => 
			array (
				'id' => 69,
				'user_id' => 75,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			69 => 
			array (
				'id' => 70,
				'user_id' => 76,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			70 => 
			array (
				'id' => 71,
				'user_id' => 98,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			71 => 
			array (
				'id' => 72,
				'user_id' => 104,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			72 => 
			array (
				'id' => 73,
				'user_id' => 105,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			73 => 
			array (
				'id' => 74,
				'user_id' => 106,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			74 => 
			array (
				'id' => 75,
				'user_id' => 109,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			75 => 
			array (
				'id' => 76,
				'user_id' => 110,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			76 => 
			array (
				'id' => 77,
				'user_id' => 111,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			77 => 
			array (
				'id' => 78,
				'user_id' => 112,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			78 => 
			array (
				'id' => 79,
				'user_id' => 113,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			79 => 
			array (
				'id' => 81,
				'user_id' => 114,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			80 => 
			array (
				'id' => 82,
				'user_id' => 115,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			81 => 
			array (
				'id' => 83,
				'user_id' => 116,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			82 => 
			array (
				'id' => 87,
				'user_id' => 121,
				'ip_address' => NULL,
				'attempts' => 2,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => '2014-07-22 17:56:00',
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			83 => 
			array (
				'id' => 88,
				'user_id' => 122,
				'ip_address' => NULL,
				'attempts' => 2,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => '2014-07-23 16:51:48',
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			84 => 
			array (
				'id' => 92,
				'user_id' => 125,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			85 => 
			array (
				'id' => 93,
				'user_id' => 125,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			86 => 
			array (
				'id' => 94,
				'user_id' => 128,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
			87 => 
			array (
				'id' => 132,
				'user_id' => 175,
				'ip_address' => NULL,
				'attempts' => 0,
				'suspended' => 0,
				'banned' => 0,
				'last_attempt_at' => NULL,
				'suspended_at' => NULL,
				'banned_at' => NULL,
			),
		));
	}

}
